# Generated by Django 2.2.4 on 2019-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('car_brand', models.CharField(max_length=20)),
                ('body_type', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('manufacturing_year', models.IntegerField(default=0)),
            ],
        ),
    ]
